# Generated by Django 2.2.8 on 2019-12-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=models.ImageField(upload_to='media/img/curso'),
        ),
    ]
